/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.JuegoControlador;
import javax.swing.JLabel;

/**
 *
 * @author migue
 */
public class VistaJuego extends javax.swing.JDialog {
    
    /**
     * Creates new form VistaJuego
     */
    public VistaJuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JuegoControlador juegoControl = new JuegoControlador(this);
    }

    public JLabel getCaballoLabel() {
        return caballoLabel;
    }

    public JLabel getDelfinLabel() {
        return delfinLabel;
    }

    public JLabel getGalloLabel() {
        return galloLabel;
    }

    public JLabel getGatoLabel() {
        return gatoLabel;
    }

    public JLabel getOvejaLabel() {
        return ovejaLabel;
    }

    public JLabel getPatoLabel() {
        return patoLabel;
    }

    public JLabel getPerroLabel() {
        return perroLabel;
    }

    public JLabel getVacaLabel() {
        return vacaLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        perroLabel = new javax.swing.JLabel();
        gatoLabel = new javax.swing.JLabel();
        vacaLabel = new javax.swing.JLabel();
        patoLabel = new javax.swing.JLabel();
        caballoLabel = new javax.swing.JLabel();
        ovejaLabel = new javax.swing.JLabel();
        galloLabel = new javax.swing.JLabel();
        delfinLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(VistaJuego.class, "VistaJuego.title")); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2, 20, 20));

        perroLabel.setText("Perro");
        getContentPane().add(perroLabel);

        gatoLabel.setText("Gato");
        getContentPane().add(gatoLabel);

        vacaLabel.setText("Vaca");
        getContentPane().add(vacaLabel);

        patoLabel.setText("Pato");
        getContentPane().add(patoLabel);

        caballoLabel.setText("Caballo");
        getContentPane().add(caballoLabel);

        ovejaLabel.setText("Oveja");
        getContentPane().add(ovejaLabel);

        galloLabel.setText("Gallo");
        getContentPane().add(galloLabel);

        delfinLabel.setText("Delfin");
        getContentPane().add(delfinLabel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaJuego dialog = new VistaJuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caballoLabel;
    private javax.swing.JLabel delfinLabel;
    private javax.swing.JLabel galloLabel;
    private javax.swing.JLabel gatoLabel;
    private javax.swing.JLabel ovejaLabel;
    private javax.swing.JLabel patoLabel;
    private javax.swing.JLabel perroLabel;
    private javax.swing.JLabel vacaLabel;
    // End of variables declaration//GEN-END:variables
}
