/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import org.netbeans.validation.api.ui.swing.ValidationPanel;

/**
 *
 * @author migue
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    public JPanel getDatosPane() {
        return datosPane;
    }

    public JLabel getDireccionLabel() {
        return direccionLabel;
    }

    public JTextField getDireccionTextField() {
        return direccionTextField;
    }

    public JButton getEliminarAlumnoButton() {
        return eliminarAlumnoButton;
    }

    public JLabel getFechaLabel() {
        return fechaLabel;
    }

    public JTextField getFechaTextField() {
        return fechaTextField;
    }

    public JPanel getFormularioPane() {
        return formularioPane;
    }

    public JButton getInsertarAlumnoButton() {
        return insertarAlumnoButton;
    }

    public JPanel getJuegoPane() {
        return juegoPane;
    }

    public JButton getLimpiarButton() {
        return limpiarButton;
    }

    public JLabel getNombreLabel() {
        return nombreLabel;
    }

    public JTextField getNombreTextField() {
        return nombreTextField;
    }

    public JTabbedPane getTabbedPane() {
        return tabbedPane;
    }

    public JTable getTabla() {
        return tabla;
    }

    public JScrollPane getTablaPane() {
        return tablaPane;
    }

    public JLabel getTelefonoLabel() {
        return telefonoLabel;
    }

    public JTextField getTelefonoTextField() {
        return telefonoTextField;
    }

    public JLabel getTutorLabel() {
        return tutorLabel;
    }

    public JTextField getTutorTextField() {
        return tutorTextField;
    }

    public ValidationPanel getValidationPane() {
        return validationPane;
    }

    public JButton getModificarAlumnoButton() {
        return modificarAlumnoButton;
    }

    public JButton getJuegoButton() {
        return juegoButton;
    }

    public JPanel getLocalizacionPane() {
        return localizacionPane;
    }

    public JLabel getLocalizacionLabel() {
        return localizacionLabel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        formularioPane = new javax.swing.JPanel();
        datosPane = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        fechaTextField = new javax.swing.JTextField();
        direccionLabel = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        telefonoLabel = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        tutorLabel = new javax.swing.JLabel();
        tutorTextField = new javax.swing.JTextField();
        tablaPane = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        validationPane = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        limpiarButton = new javax.swing.JButton();
        modificarAlumnoButton = new javax.swing.JButton();
        eliminarAlumnoButton = new javax.swing.JButton();
        insertarAlumnoButton = new javax.swing.JButton();
        juegoPane = new javax.swing.JPanel();
        juegoButton = new javax.swing.JButton();
        textoLabel = new javax.swing.JLabel();
        localizacionPane = new javax.swing.JPanel();
        localizacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guardería Nervión");
        setPreferredSize(new java.awt.Dimension(500, 480));
        setResizable(false);

        formularioPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        datosPane.setLayout(new java.awt.GridLayout(5, 0, 0, 20));

        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreLabel.setText("Nombre del alumno:");
        datosPane.add(nombreLabel);

        nombreTextField.setName("Nombre del alumno"); // NOI18N
        datosPane.add(nombreTextField);

        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fechaLabel.setText("Fecha de nacimiento:");
        datosPane.add(fechaLabel);

        fechaTextField.setName("Fecha de nacimiento"); // NOI18N
        datosPane.add(fechaTextField);

        direccionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        direccionLabel.setText("Dirección:");
        datosPane.add(direccionLabel);

        direccionTextField.setName("Dirección"); // NOI18N
        datosPane.add(direccionTextField);

        telefonoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telefonoLabel.setText("Teléfono del tutor:");
        datosPane.add(telefonoLabel);

        telefonoTextField.setName("Teléfono del tutor"); // NOI18N
        datosPane.add(telefonoTextField);

        tutorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tutorLabel.setText("Nombre del tutor:");
        datosPane.add(tutorLabel);

        tutorTextField.setName("Nombre del tutor"); // NOI18N
        datosPane.add(tutorTextField);

        formularioPane.add(datosPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 190));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jose Ruso", "01-10-2015", "Calle Falsa 123", "555320130", "Manolo Torres"},
                {"Alvaro Barrasa", "09-04-2016", "Avd Faraon s/n", "555123456", "Antonio Paez"}
            },
            new String [] {
                "Nombre Alumno", "Fecha de Nacimiento", "Dirección", "Teléfono Tutor", "Nombre Tutor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPane.setViewportView(tabla);

        formularioPane.add(tablaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 120));
        formularioPane.add(validationPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 420, 20));

        limpiarButton.setText("Limpiar campos");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });
        formularioPane.add(limpiarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        modificarAlumnoButton.setText("Modificar alumno");
        formularioPane.add(modificarAlumnoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        eliminarAlumnoButton.setText("Eliminar alumno");
        formularioPane.add(eliminarAlumnoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        insertarAlumnoButton.setText("Insertar alumno");
        formularioPane.add(insertarAlumnoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        tabbedPane.addTab("Formulario Alumnos", formularioPane);

        juegoPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        juegoButton.setText("Iniciar Juego");
        juegoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoButtonActionPerformed(evt);
            }
        });
        juegoPane.add(juegoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, 60));

        textoLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        textoLabel.setForeground(new java.awt.Color(51, 51, 51));
        textoLabel.setText("<html><p>Este minijuego está indicado para niños con una edad entre 0 y 5 años. </p><p>En él aparecen imágenes de animales que reproducirán el sonido carácteristico de cada animal cuando hagamos click en ellas.</p><br/><p> Para iniciar el juego solo hay que pinchar en el botón de abajo.</p></html>");
        textoLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        juegoPane.add(textoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 410, 210));

        tabbedPane.addTab("Juego Animales", juegoPane);

        localizacionPane.setLayout(new java.awt.GridLayout(1, 0));
        localizacionPane.add(localizacionLabel);

        tabbedPane.addTab("Dónde estamos", localizacionPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void juegoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoButtonActionPerformed
        
        VistaJuego juego = new VistaJuego(this, true);
        juego.setVisible(true);
    }//GEN-LAST:event_juegoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                VistaPrincipal principal = new VistaPrincipal();
                
                principal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel datosPane;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JButton eliminarAlumnoButton;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField fechaTextField;
    private javax.swing.JPanel formularioPane;
    private javax.swing.JButton insertarAlumnoButton;
    private javax.swing.JButton juegoButton;
    private javax.swing.JPanel juegoPane;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JLabel localizacionLabel;
    private javax.swing.JPanel localizacionPane;
    private javax.swing.JButton modificarAlumnoButton;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tabla;
    private javax.swing.JScrollPane tablaPane;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.JLabel textoLabel;
    private javax.swing.JLabel tutorLabel;
    private javax.swing.JTextField tutorTextField;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPane;
    // End of variables declaration//GEN-END:variables
}
